# constants.tf
locals {
  machine_map = {
    machines = {
      control-plane = {
        name                = "control-plane"
        target_node         = "nova"                                     # Name of the Proxmox Server
        vmid                = "3020"                                     # Promox VM ID
        qemu_os             = "other"                                    # Type of Operating System
        os_type             = "cloud-init"                               # Set to cloud-init to utilize templates
        agent               = 1                                          # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone          = true                                       # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template            = "tmpl-ubuntu-server-22.04-jammy-jellyfish" # Name of Template Used to Clone
        cores               = 2
        socket              = 2
        memory              = 8192
        cpu                 = "host"
        scsihw              = "virtio-scsi-pci"
        bootdisk            = "scsi0"
        storage             = "150G" # Size of Secondary hard drive assiged as bootable
        ip_address          = "172.16.30.20"
        gateway             = "172.16.30.1"
        vlan_num            = 30
        description         = "Kubernetes Control Plane"
        ssh_user            = "ubuntu"
        mac_address         = "02:07:14:b4:37:20"
        disk_type           = "virtio"
        storage_dev         = "local-thin"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ubuntu"
        automatic_reboot    = true
        onboot              = true
        network_firewall    = false #defaults to false
        network_tag         = 30
        dns_servers         = "172.16.30.1 1.1.1.1 127.0.0.1"
        searchdomain        = "k8s.hl.lunarops.net"
      }
      worker-1 = {
        name                = "worker-1"
        target_node         = "nova"                                     # Name of the Proxmox Server
        vmid                = "3021"                                     # Promox VM ID
        qemu_os             = "other"                                    # Type of Operating System
        os_type             = "cloud-init"                               # Set to cloud-init to utilize templates
        agent               = 1                                          # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone          = true                                       # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template            = "tmpl-ubuntu-server-22.04-jammy-jellyfish" # Name of Template Used to Clone
        cores               = 2
        socket              = 2
        memory              = 8192
        cpu                 = "host"
        scsihw              = "virtio-scsi-pci"
        bootdisk            = "scsi0"
        storage             = "150G" # Size of Secondary hard drive assiged as bootable
        ip_address          = "172.16.30.21"
        gateway             = "172.16.30.1"
        vlan_num            = 30
        description         = "Kubernetes Worker"
        ssh_user            = "ubuntu"
        mac_address         = "02:07:14:b4:37:21"
        disk_type           = "virtio"
        storage_dev         = "local-thin"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ubuntu"
        automatic_reboot    = true
        onboot              = true
        network_firewall    = false #defaults to false
        network_tag         = 30
        dns_servers         = "172.16.30.1 1.1.1.1 127.0.0.1"
        searchdomain        = "k8s.hl.lunarops.net"
      }
      worker-2 = {
        name                = "worker-2"
        target_node         = "nova"                                     # Name of the Proxmox Server
        vmid                = "3022"                                     # Promox VM ID
        qemu_os             = "other"                                    # Type of Operating System
        os_type             = "cloud-init"                               # Set to cloud-init to utilize templates
        agent               = 1                                          # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone          = true                                       # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template            = "tmpl-ubuntu-server-22.04-jammy-jellyfish" # Name of Template Used to Clone
        cores               = 2
        socket              = 2
        memory              = 8192
        cpu                 = "host"
        scsihw              = "virtio-scsi-pci"
        bootdisk            = "scsi0"
        storage             = "150G" # Size of Secondary hard drive assiged as bootable
        ip_address          = "172.16.30.22"
        gateway             = "172.16.30.1"
        vlan_num            = 30
        description         = "Kubernetes Worker"
        ssh_user            = "ubuntu"
        mac_address         = "02:07:14:b4:37:22"
        disk_type           = "virtio"
        storage_dev         = "local-thin"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ubuntu"
        automatic_reboot    = true
        onboot              = true
        network_firewall    = false #defaults to false
        network_tag         = 30
        dns_servers         = "172.16.30.1 1.1.1.1 127.0.0.1"
        searchdomain        = "k8s.hl.lunarops.net"
      }
      worker-3 = {
        name                = "worker-3"
        target_node         = "nova"                                     # Name of the Proxmox Server
        vmid                = "3023"                                     # Promox VM ID
        qemu_os             = "other"                                    # Type of Operating System
        os_type             = "cloud-init"                               # Set to cloud-init to utilize templates
        agent               = 1                                          # Set to 1 to enable the QEMU Guest Agent. Note, you must run the qemu-guest-agent daemon in the guest for this to have any effect.
        full_clone          = true                                       # Set to true to create a full clone, or false to create a linked clone. See the docs about cloning for more info. Only applies when clone is set.
        template            = "tmpl-ubuntu-server-22.04-jammy-jellyfish" # Name of Template Used to Clone
        cores               = 2
        socket              = 2
        memory              = 8192
        cpu                 = "host"
        scsihw              = "virtio-scsi-pci"
        bootdisk            = "scsi0"
        storage             = "150G" # Size of Secondary hard drive assiged as bootable
        ip_address          = "172.16.30.23"
        gateway             = "172.16.30.1"
        vlan_num            = 30
        description         = "Kubernetes Worker"
        ssh_user            = "ubuntu"
        mac_address         = "02:07:14:b4:37:23"
        disk_type           = "virtio"
        storage_dev         = "local-thin"
        network_bridge_type = "vmbr0"
        network_model       = "virtio"
        cloud_init_pass     = "ubuntu"
        automatic_reboot    = true
        onboot              = true
        network_firewall    = false #defaults to false
        network_tag         = 30
        dns_servers         = "172.16.30.1 1.1.1.1 127.0.0.1"
        searchdomain        = "k8s.hl.lunarops.net"
      }
    }
  }

  machines = lookup(local.machine_map, "machines", {})
}
